# gsheets-accounting.lobster.yaml
# Google Sheets accounting workflow using gog CLI
name: gsheets-accounting
version: "1.0"
description: Append and verify accounting entries in Google Sheets using the gog CLI

trigger:
  type: manual

env:
  SHEET_ID: ${SHEET_ID:-1eq5Gw5CElkVz5UTb45_RlIpRp_rb1jKrEq6okZUvas8}
  SHEET_NAME: ${SHEET_NAME:-Transactions}
  GOG_CMD: ${GOG_CMD:-gog}

inputs:
  row:
    type: object
    required: true
    description: "Row data object with fields: date, type, category, description, amount, reference, status"
  sheet_id:
    type: string
    required: false
    description: Override default sheet ID

steps:
  - id: validate-auth
    name: Check gog CLI authentication
    action: shell
    command: |
      # Verify gog CLI is available and authenticated
      if ! command -v ${GOG_CMD} >/dev/null 2>&1; then
        echo '{"error": "gog CLI not found in PATH"}'
        exit 1
      fi
      # Test authentication by reading sheet metadata
      sheet_id="${inputs.sheet_id:-${SHEET_ID}}"
      auth_check=$(${GOG_CMD} sheets get "$sheet_id" --format json 2>&1) || {
        echo "{\"error\": \"gog authentication failed\", \"details\": \"$auth_check\"}"
        exit 1
      }
      echo '{"authenticated": true, "sheet_id": "'"$sheet_id"'"}'
    validation:
      - check: exit_code
        expect: 0
      - check: stdout_contains
        expect: "authenticated"
    on_failure:
      action: abort
      notification:
        type: log
        message: "Google Sheets authentication failed - check gog CLI configuration"
    outputs:
      auth_status: ${stdout}

  - id: validate-data
    name: Validate row data format and required fields
    depends_on: [validate-auth]
    action: shell
    command: |
      # Validate the row data has required fields
      row_json='${inputs.row}'
      required_fields="date type amount"
      missing=""
      for field in $required_fields; do
        value=$(echo "$row_json" | jq -r ".${field} // empty")
        if [ -z "$value" ]; then
          missing="$missing $field"
        fi
      done
      if [ -n "$missing" ]; then
        echo "{\"error\": \"Missing required fields:${missing}\"}"
        exit 1
      fi
      # Validate date format (ISO 8601 or YYYY-MM-DD)
      date_val=$(echo "$row_json" | jq -r '.date')
      if ! echo "$date_val" | grep -qE '^[0-9]{4}-[0-9]{2}-[0-9]{2}'; then
        echo '{"error": "Invalid date format, expected YYYY-MM-DD or ISO 8601"}'
        exit 1
      fi
      echo '{"valid": true, "fields": '"$row_json"'}'
    validation:
      - check: exit_code
        expect: 0
      - check: stdout_contains
        expect: "valid"
    on_failure:
      action: abort
      notification:
        type: log
        message: "Row data validation failed"
    outputs:
      validated_data: ${stdout}

  - id: append-row
    name: Append row to Google Sheet
    depends_on: [validate-data]
    action: shell
    command: |
      # Build row values from input data
      sheet_id="${inputs.sheet_id:-${SHEET_ID}}"
      row_json='${inputs.row}'
      date=$(echo "$row_json" | jq -r '.date // ""')
      type=$(echo "$row_json" | jq -r '.type // ""')
      category=$(echo "$row_json" | jq -r '.category // ""')
      description=$(echo "$row_json" | jq -r '.description // ""')
      amount=$(echo "$row_json" | jq -r '.amount // ""')
      reference=$(echo "$row_json" | jq -r '.reference // ""')
      status=$(echo "$row_json" | jq -r '.status // ""')

      # Append using gog CLI
      result=$(${GOG_CMD} sheets append "$sheet_id" "${SHEET_NAME}" \
        --values "$date" "$type" "$category" "$description" "$amount" "$reference" "$status" \
        --format json 2>&1) || {
        echo "{\"error\": \"Failed to append row\", \"details\": \"$result\"}"
        exit 1
      }
      echo "$result"
    validation:
      - check: exit_code
        expect: 0
    on_failure:
      action: retry
      retry_count: 3
      retry_delay: 5s
    outputs:
      append_result: ${stdout}

  - id: verify-entry
    name: Read back appended row to confirm
    depends_on: [append-row]
    action: shell
    command: |
      # Verify the entry was appended by reading the last row
      sheet_id="${inputs.sheet_id:-${SHEET_ID}}"
      last_row=$(${GOG_CMD} sheets read "$sheet_id" "${SHEET_NAME}" \
        --range "last" \
        --format json 2>&1) || {
        echo "{\"error\": \"Failed to read back entry\", \"details\": \"$last_row\"}"
        exit 1
      }
      # Verify the reference field matches
      row_json='${inputs.row}'
      expected_ref=$(echo "$row_json" | jq -r '.reference // ""')
      actual_ref=$(echo "$last_row" | jq -r '.[0].reference // .[0][5] // ""')
      if [ -n "$expected_ref" ] && [ "$expected_ref" != "$actual_ref" ]; then
        echo "{\"warning\": \"Reference mismatch\", \"expected\": \"$expected_ref\", \"actual\": \"$actual_ref\", \"row\": $last_row}"
      else
        echo "{\"verified\": true, \"row\": $last_row}"
      fi
    validation:
      - check: exit_code
        expect: 0
    on_failure:
      action: notify
      notification:
        type: log
        message: "Entry verification failed - row may have been appended but could not be confirmed"
    outputs:
      verification: ${stdout}

error_handling:
  default_action: abort
  notification:
    type: log
    message: "Google Sheets accounting workflow failed at step ${failed_step}: ${error_message}"
